### ISSUE TITLE
Give PR to ryoko's repo 给ryoko发PR

### ISSUE THREAD

**Issue by wendavid552** [DreamingLri/masa-mods-chinese#1]
不知道有没有兴趣给官方版本贡献翻译（

**Comment by DreamingLri** [comment]
感谢您的建议，目前有提交pr的打算，还是等汉化完善之后（是的，现在还有很多bug）再考虑提交吧

---

Thank you for your suggestion. I do plan to submit a PR, but I'll wait until the Chinese translation is more complete (yes, there are still a lot of bugs) before considering it.

**Comment by wendavid552** [comment]
没事，完全可以开个draft占坑，毕竟之前合并的那套翻译还是有改进空间的（）

**Comment by zly2006** [comment]
@DreamingLri 请问目前有这方面的计划吗？我和Sakura ryoko讨论后认为你们的工作非常有意义，而且确实有很多人在模组那边问中文翻译的事情，最近还有人提交了一堆机翻过去……不管你们做的如何，我都非常希望你们能把这个翻译合并进去

如果有可能的话，我会尽量参与一些翻译，能顺手改的肯定会直接PR了，但是不保证该改的全部改了，可能需要大家review的时候上点心，看看有没有同类错误还没改。在这些工作完成后，我希望先把tweakeroo的翻译合并了。

我还是希望你们再考虑一下，目前除了tweakeroo应该都内置包括了中文翻译，对于已有的内容如果有和你们翻译不同的可以对照改进；如果需要什么帮助或者功能不确定，欢迎随时找我帮你们翻源码。

**Comment by DreamingLri** [comment]
> @DreamingLri 请问目前有这方面的计划吗？我和Sakura ryoko讨论后认为你们的工作非常有意义，而且确实有很多人在模组那边问中文翻译的事情，最近还有人提交了一堆机翻过去……不管你们做的如何，我都非常希望你们能把这个翻译合并进去
> 
> 
> 
> 如果有可能的话，我会尽量参与一些翻译，能顺手改的肯定会直接PR了，但是不保证该改的全部改了，可能需要大家review的时候上点心，看看有没有同类错误还没改。在这些工作完成后，我希望先把tweakeroo的翻译合并了。
> 
> 
> 
> 我还是希望你们再考虑一下，目前除了tweakeroo应该都内置包括了中文翻译，对于已有的内容如果有和你们翻译不同的可以对照改进；如果需要什么帮助或者功能不确定，欢迎随时找我帮你们翻源码。

完全没问题，有空我把tweakeroo的中文翻译提一个PR过去，繁体汉化我的建议是直接采取我们这一版，毕竟以前提交的大部分内容也都是本仓库另一位作者的汉化（甚至还是盗传的），都可以讨论的

**Comment by zly2006** [comment]
有一点需要注意：我和Sakura都同意英语不应该保留在翻译后内容中，这些英语内容普遍被截断了，不能完整地表达意思

建议新建一个分支搞这个

**Comment by DreamingLri** [comment]
> 有一点需要注意：我和Sakura都同意英语不应该保留在翻译后内容中，这些英语内容普遍被截断了，不能完整地表达意思
> 
> 
> 
> 建议新建一个分支搞这个

这个我们也考虑过，所以做了neo版本（纯中文版），到时候提PR肯定是提供neo版本的内容的，现在还保留英文前缀只是继承醉梦巅峰那版汉化的格式习惯而已

**Comment by DreamingLri** [comment]
但是sakura那边的模组好多翻译都很poor，至少日语是这样的，也有使用者反应了这一[情况](https://github.com/maruohon/tweakeroo/issues/529)

可不可以暂时不要新增没有review的翻译了（只是提一个小小的建议）

**Comment by zly2006** [comment]
> 但是sakura那边的模组好多翻译都很poor，至少日语是这样的，也有使用者反应了这一[情况](https://github.com/maruohon/tweakeroo/issues/529)
> 
> 可不可以暂时不要新增没有review的翻译了（只是提一个小小的建议）

是的，所以她发了一个版本就revert了 😂

**Comment by DreamingLri** [comment]
或许我们可以拉一个小群来讨论这个，这里是我的[telegram](https://t.me/DreamingLri)账号，我和繁体汉化的作者平时用这个交流
