### ISSUE TITLE
投影部分未汉化，如图1

### ISSUE THREAD

**Issue by Hoicey522** [DreamingLri/masa-mods-chinese#12]
![image](https://github.com/user-attachments/assets/a287870a-81ee-4691-bb53-5d6e77c6c075)
![image](https://github.com/user-attachments/assets/1e9d7534-d852-4336-b6d1-538f8eb85583)

**Comment by Hoicey522** [comment]
补充：投影右上角侧未汉化
![屏幕截图 2024-11-09 120733](https://github.com/user-attachments/assets/1d380a01-9938-4af0-8302-9a8ac51a2487)

**Comment by DreamingLri** [comment]
我翻阅了源代码

图1的翻译无法实现，因为是硬编码写死在代码内部
![image](https://github.com/user-attachments/assets/17c92599-182d-4fa7-af94-b33485790bf7)

---

不知道您指的图2的未翻译内容是哪里，最上面那个是版本号，不需要进行翻译

---

图3的翻译同图1
![image](https://github.com/user-attachments/assets/a4f46100-0a78-4afe-a74c-752cb3f580f3)

**Comment by DreamingLri** [comment]
我回来大概会给Sakura提一个PR去修复这些硬编码问题

**Comment by Hoicey522** [comment]
> 我翻阅了源代码
> 
> 图1的翻译无法实现，因为是硬编码写死在代码内部 ![image](https://private-user-images.githubusercontent.com/63730641/384687897-17c92599-182d-4fa7-af94-b33485790bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDU1ODEsIm5iZiI6MTczMTI0NTI4MSwicGF0aCI6Ii82MzczMDY0MS8zODQ2ODc4OTctMTdjOTI1OTktMTgyZC00ZmE3LWFmOTQtYjMzNDg1NzkwYmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEzMjgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMmU0Njk3ODE4N2Q4Yjk0ZjE4M2Y1NDQ0ZjBlYTIwMmYzMDY4YzIxZDMxNDQxYzRhZDYxZGRhZjhlNzA1ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GCe8CfGyWqhi7eqLNT8DYWZq8bMOTdrTPtEL6FaKSKo)
> 
> 不知道您指的图2的未翻译内容是哪里，最上面那个是版本号，不需要进行翻译
> 
> 图3的翻译同图1 ![image](https://private-user-images.githubusercontent.com/63730641/384688022-a4f46100-0a78-4afe-a74c-752cb3f580f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDU1ODEsIm5iZiI6MTczMTI0NTI4MSwicGF0aCI6Ii82MzczMDY0MS8zODQ2ODgwMjItYTRmNDYxMDAtMGE3OC00YWZlLWE3NGMtNzUyY2IzZjU4MGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEzMjgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzODM4NjZiNjIzMDk1NjdjYjg3YWM1YmI4MjEzMTEyMDYwNTMwYjM2NDQ2MGUyMTlhYmNkOTU5MDgyYWNhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.94-fOhrO1ouVzxCyeCF_-erBWX0SlfbfSLZwkE7tuFA)

![49bb6ae6-d88b-4f1b-9ab3-2ac7ed09e3f2](https://github.com/user-attachments/assets/1ddd4a69-b4d8-4785-ae31-fc7a8b1e91ad)
 图中红框的地方

**Comment by Hoicey522** [comment]
如果无法翻译，那就等sr那边修复吧

**Comment by Hoicey522** [comment]
![image](https://github.com/user-attachments/assets/063c27ed-60b9-46f7-8ec7-a3befb9e6674)

鼠标悬浮显示的“SB”能否汉化，虽然我知道是盒的意思。

_怎么还骂人呢？（bushi_

**Comment by DreamingLri** [comment]
问题不大，但是这种与原主题不同的建议另开一个issue，不然我可能会看串（眼花导致的）

看到了邮件，然后在issue里面找半天，结果在这找到了（

**Comment by DreamingLri** [comment]
已向 Sakura 提交 [PR](https://github.com/sakura-ryoko/litematica/pull/97)，等待合并

**Comment by DreamingLri** [comment]
那个`SB`的问题会和硬编码一起合并发布新版本

**Comment by DreamingLri** [comment]
已在 [v1.3.5](https://github.com/DreamingLri/masa-mods-chinese/releases/tag/v1.3.5)中修复，`litematica`的硬编码问题需要等待Sakura发新版本
