### ISSUE TITLE
[错误翻译 | v1.3.5] MiniHUD的"蜂蜜"信息翻译与"蜜蜂"信息一致 (The bee is sus! ;\ )

### ISSUE THREAD

**Issue by NorthZeroD** [DreamingLri/masa-mods-chinese#14]
错误发生在：MiniHUD设置 - 信息 - HoneyLevel(蜂蜜等级信息)

v1.3.5中的错误翻译：
![wrong](https://github.com/user-attachments/assets/10ae01bf-8b2d-4a63-828d-8a4e67c31251)

预期中的正确翻译：
![right](https://github.com/user-attachments/assets/32759aec-64a9-4108-ba1d-5e1380384ad0)

sus ;\

**Comment by DreamingLri** [comment]
感谢您的反馈❤️
会在下个版本中进行修复

**Comment by DreamingLri** [comment]
大抵是翻译的时候眼花了（目移）

**Comment by snowlinouo** [comment]
已修復 https://github.com/DreamingLri/masa-mods-chinese/commit/8b56c175df1bc7d698b28f178dfab29468ca7659

下版本上線，感謝回報！
