### ISSUE TITLE
翻譯問題

### ISSUE THREAD

**Issue by notlin4** [DreamingLri/masa-mods-chinese#16]
https://github.com/DreamingLri/masa-mods-chinese/blob/1195c00d263cc2636b37868ed43033bac8dc6da1/masa-mods-chinese/en_us/malilib.json#L81
https://github.com/DreamingLri/masa-mods-chinese/blob/1195c00d263cc2636b37868ed43033bac8dc6da1/masa-mods-chinese/zh_cn/malilib.json#L66
https://github.com/DreamingLri/masa-mods-chinese/blob/1195c00d263cc2636b37868ed43033bac8dc6da1/masa-mods-chinese/zh_tw/malilib.json#L66
應為「允許空的按鍵綁定」

**Comment by DreamingLri** [comment]
感谢您的反馈❤️

已在 [`268fa7c
`](https://github.com/DreamingLri/masa-mods-chinese/commit/268fa7c4bbf3d586bcef4e11aa14d7d9b08073bf) 中修复

会在下个版本发布更正的内容
