### ISSUE TITLE
Litematica Printer翻译无效

### ISSUE THREAD

**Issue by wkamtuta** [DreamingLri/masa-mods-chinese#18]
资源包里有Litematica Printer翻译，但mod是硬编码，不能起到效果

**Comment by DreamingLri** [comment]
litematica版本是多少，从1.21版本之后似乎都不是硬编码了

**Comment by wkamtuta** [comment]
> litematica版本是多少，从1.21版本之后似乎都不是硬编码了

GitHub的最新的1.21-3.2.1-fabric版本,assets里没有language，只有图标图片

**Comment by DreamingLri** [comment]
事实上都存在，这里是1.21的[源代码](https://github.com/sakura-ryoko/litematica-printer/tree/1.21/src/main/resources/assets/litematica-printer/lang)，我猜你的模组里面不存在是因为sakura曾经大规模删除了翻译文件（是一段黑历史）

你更新到最新版的1.21 `litematica-printer` 就好了，这里是[下载链接](https://github.com/sakura-ryoko/litematica-printer/releases/tag/1.21-sakura.7)

**Comment by DreamingLri** [comment]
如果更新到最新版没有问题的话，我就关闭这个issue了❤️

**Comment by wkamtuta** [comment]
> 如果更新到最新版没有问题的话，我就关闭这个issue了❤️

明白了，sakura版本的才能有效
谢谢您！回复太迅速了！
