### ISSUE TITLE
为重复的功能提供一个特殊版本

### ISSUE THREAD

**Issue by Cassy-Lee** [DreamingLri/masa-mods-chinese#6]
是否可以提供一个用于tweakermore的版本
来自Fallen的tweakermore模组提供了一个可以使malilib的配置界面同时显示译名与选项的方法

**Comment by Cassy-Lee** [comment]
有了tweakermore后可以删除前面的英文名和竖线

**Comment by DreamingLri** [comment]
完全没问题，这个实现很简单

**Comment by DreamingLri** [comment]
在[v1.2.3](https://github.com/DreamingLri/masa-mods-chinese/releases/tag/v1.2.3)中已实现
