### ISSUE TITLE
支援繁體中文詢問

### ISSUE THREAD

**Issue by snowlinouo** [DreamingLri/masa-mods-chinese#8]
作者你好，我是在 Modrinth 上更新 [Masa Family Bucket Translation Pack](https://modrinth.com/resourcepack/masa-family-bucket-translationpack) 漢化資源包版本的作者

我在作者你做這個之前的去年時有詢問「醉梦巅峰」是否能進行簡體轉繁體並在地化的工作 ([當初問原作者的紀錄](https://imgur.com/XJ5KeEM))
後來就在 Modrinth 上更新繁體及簡體的服務部分，後續也有自己更新修復一些錯誤及新增翻譯的部分
這邊想詢問我是否能進行繁體在地化的更新服務呢

感謝作者！

如果這邊作者同意，這邊也會記錄下來至 Modrinth 的頁面上記錄作者的名稱這樣

**Comment by DreamingLri** [comment]
完全没有问题哒awa

**Comment by DreamingLri** [comment]
我和醉梦巅峰的想法是一样的，我本人并不是很熟悉繁体中文，所以专业的事就交给专业的人来做就好啦

**Comment by DreamingLri** [comment]
不过需要注意一点，我这个汉化包只能支持1.21版本的mod，其它版本会出问题

**Comment by snowlinouo** [comment]
> 不过需要注意一点，我这个汉化包只能支持1.21版本的mod，其它版本会出问题

好，我再觀察看看，感謝作者！

**Comment by snowlinouo** [comment]
這邊想詢問作者，有需要幫忙「半形改全形，中英文前後新增空白區隔」的部分嗎?
這邊想要統一一下翻譯的問題，看到內容裡面蠻多中英文前後有些有空格或沒空格的問題www

**Comment by DreamingLri** [comment]
啊嘞？有些确实没有注意到x，不过我会改改的awa，原翻译文本随便改的其实

**Comment by snowlinouo** [comment]
哈哈XDD
沒事www，我這邊改繁體順便幫忙一起改就好了ww
到時候發一份給你ww

**Comment by DreamingLri** [comment]
> 哈哈XDD
> 沒事www，我這邊改繁體順便幫忙一起改就好了ww
> 到時候發一份給你ww

谢谢大佬www

**Comment by snowlinouo** [comment]
這邊我用好了，也新增繁體中文了，可以查看個#
https://github.com/snowlinouo/Masa-Mods-Translation-Pack

我這邊也有新增我之前用的 Masa Gadget 部分

沒問題我就發 Pull  簡體部分，繁體我也要一起發嗎(?

**Comment by DreamingLri** [comment]
> 這邊我用好了，也新增繁體中文了，可以查看個# https://github.com/snowlinouo/Masa-Mods-Translation-Pack
> 
> 我這邊也有新增我之前用的 Masa Gadget 部分
> 
> 沒問題我就發 Pull 簡體部分，繁體我也要一起發嗎(?

我直接手动拉取吧awa，毕竟新增繁体可能需要改进一下项目结构，麻烦大佬了

**Comment by snowlinouo** [comment]
> 我直接手动拉取吧awa，毕竟新增繁体可能需要改进一下项目结构，麻烦大佬了

哈哈哈www
我自己有改 generate.py 檔案拉，我自己邊翻譯邊生成測試翻譯都正常ww
檔案結構有 zh_cn 跟 zh_tw 的檔案#

**Comment by snowlinouo** [comment]
看到你有更改翻譯www
晚點來去更動一下好了ww

**Comment by snowlinouo** [comment]
https://github.com/snowlinouo/masa-mods-chinese

最終成品弄好了！
給作者#

看作者要怎拉(?

**Comment by DreamingLri** [comment]
> https://github.com/snowlinouo/masa-mods-chinese
> 
> 最終成品弄好了！
> 給作者#
> 
> 看作者要怎拉(?
> 

我晚上统一弄一下，顺带搞一下crowdin的配置awa

**Comment by DreamingLri** [comment]
> > https://github.com/snowlinouo/masa-mods-chinese
> > 
> > 最終成品弄好了！
> > 給作者#
> > 
> > 看作者要怎拉(?
> > 
> 
> 我晚上统一弄一下，顺带搞一下crowdin的配置awa

可能需要大佬提供一下邮箱地址，我邀请您来crowdin进行翻译awa

**Comment by snowlinouo** [comment]
> 可能需要大佬提供一下邮箱地址，我邀请您来crowdin进行翻译awa

我的信箱：
yenhank0531@gmail.com

**Comment by DreamingLri** [comment]
> > 可能需要大佬提供一下邮箱地址，我邀请您来crowdin进行翻译awa
> 
> 我的信箱：
> yenhank0531@gmail.com

我晚一些邀请您，现在在上课www

**Comment by DreamingLri** [comment]
已经修改好啦，现在支持繁体中文啦❤️

**Comment by snowlinouo** [comment]
這邊有看到Github 及 Crowdin 的邀請了！

**Comment by snowlinouo** [comment]
話說大大有甚麼溝通軟體之類的嗎www
一直用 Github 聊好奇怪XDD

**Comment by DreamingLri** [comment]
我主页有我的Telegram账号awa
Twitter也有，看大佬哪个方便，我这两个都行的

**Comment by snowlinouo** [comment]
> 我主页有我的Telegram账号awa Twitter也有，看大佬哪个方便，我这两个都行的

我發 TG 了#
