### ISSUE TITLE
错误的翻译

### ISSUE THREAD

**Issue by Cassy-Lee** [DreamingLri/masa-mods-chinese#9]
Tweakeroo>禁用类功能>禁用怪物生成渲染 名称与描述翻译错误
翻译项名称分别是
`tweakeroo.config.disable.name.disableMobSpawnerMobRendering`
`tweakeroo.config.disable.comment.disableMobSpawnerMobRendering`
该选项实际意义为 禁用刷怪笼方块实体渲染（禁用刷怪笼内实体模型渲染）
实际生效源码参考在`https://github.com/sakura-ryoko/tweakeroo/blob/c94fe7e60032d1984e97bfec60926444929a2860/src/main/java/fi/dy/masa/tweakeroo/mixin/MixinMobSpawnerBlockEntityRenderer.java#L17`
建议译名为 禁用刷怪笼渲染
建议描述为 禁用刷怪笼内实体模型渲染

**Comment by DreamingLri** [comment]
感谢您的贡献
已在 [v1.3.2](https://github.com/DreamingLri/masa-mods-chinese/releases/tag/v1.3.2)中修复❤️
